version: "3.1"
services:
  frontend:
    build: frontend
    restart: always
    container_name: my-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - react-express
    depends_on:
      - backend
  backend:
    container_name: my-backend
    restart: always
    build: backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/sec/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    ports:
      - 3050:3050
  mongo:
    container_name: my-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    ports:
      - 27017:27017
networks:
  express-mongo:
  react-express:
  